services:
  # База данных
  db:
    image: postgres:13
    container_name: note_api_db
    environment:
      POSTGRES_DB: noteapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234abcd
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

# API приложение
  api:
    build: .
    container_name: note_api_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped


volumes:
  postgres_data: 